In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [6]:
df = pd.read_csv('credit_card_fraud_10k.csv')
df.head()

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66,3,40,0
1,2,541.82,3,Travel,1,0,87,1,64,0
2,3,237.01,17,Grocery,0,0,49,1,61,0
3,4,164.33,4,Grocery,0,1,72,3,34,0
4,5,30.53,15,Food,0,0,79,0,44,0

In [3]:
#Checking for null values in the dataset.
df.isnull().sum()

transaction_id         0
amount                 0
transaction_hour       0
merchant_category      0
foreign_transaction    0
location_mismatch      0
device_trust_score     0
velocity_last_24h      0
cardholder_age         0
is_fraud               0
dtype: int64

In [4]:
#Dropping the unwanted column ('transaction_id') from the dataset.
df.drop('transaction_id', axis=1, inplace=True)

In [5]:
df['merchant_category'].value_counts()

merchant_category
Food           2093
Clothing       2050
Travel         1990
Grocery        1944
Electronics    1923
Name: count, dtype: int64

In [7]:
# Converting the categorical column 'merchant_category' into numerical values using one-hot encoding.
# Convert text categories into 1s and 0s using dtype=int
df = pd.get_dummies(df, columns=['merchant_category'], drop_first=True, dtype=int)
print(df.head())

   transaction_id  amount  transaction_hour  foreign_transaction  \
0               1   84.47                22                    0
1               2  541.82                 3                    1
2               3  237.01                17                    0
3               4  164.33                 4                    0
4               5   30.53                15                    0

   location_mismatch  device_trust_score  velocity_last_24h  cardholder_age  \
0                  0                  66                  3              40
1                  0                  87                  1              64
2                  0                  49                  1              61
3                  1                  72                  3              34
4                  0                  79                  0              44

   is_fraud  merchant_category_Electronics  merchant_category_Food  \
0         0                              1                       0
1         0                              0                       0
2         0                              0                       0
3         0                              0                       0
4         0                              0                       1

   merchant_category_Grocery  merchant_category_Travel
0                          0                         0
1                          0                         1
2                          1                         0
3                          1                         0
4                          0                         0

In [8]:
df.head()

,transaction_id,amount,transaction_hour,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud,merchant_category_Electronics,merchant_category_Food,merchant_category_Grocery,merchant_category_Travel
0,1,84.47,22,0,0,66,3,40,0,1,0,0,0
1,2,541.82,3,1,0,87,1,64,0,0,0,0,1
2,3,237.01,17,0,0,49,1,61,0,0,0,1,0
3,4,164.33,4,0,1,72,3,34,0,0,0,1,0
4,5,30.53,15,0,0,79,0,44,0,0,1,0,0

In [9]:
df['amount']

0        84.47
1       541.82
2       237.01
3       164.33
4        30.53
         ...
9995    350.91
9996    410.04
9997    527.75
9998     91.20
9999     44.06
Name: amount, Length: 10000, dtype: float64

### This dataset has an amount column with large numbers and a foreign_transaction column with tiny numbers (0 or 1). If we leave it like this, the model will think the amount is more important just because the number is bigger. We use a scaler to normalize the data, which shrinks all the numerical columns down to a similar range.

In [10]:
# Selecting the columns/features which are required for scaling inside an variable called 'columns_to_scale'.
columns_to_scale = ['amount', 'transaction_hour', 'device_trust_score', 
                    'velocity_last_24h', 'cardholder_age']

In [11]:
#Assigning the StandardScaler() to a variable called 'scaler'.
scaler = StandardScaler()

# Applying the scaler to the selected columns/features.
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

### Now the data is perfectly clean for a machine learning model.

In [12]:
#Extacting the cleaned dataset into a new CSV file called 'cleaned_credit_card_fraud_10k.csv'.
df.to_csv('cleaned_credit_card_fraud_10k.csv', index=False)